"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const path = usePathname();
  const noLayOut = ["/auth/login", "/auth/register"];
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {!noLayOut.includes(path) && <Header />} */}
        {children}
        {/* {!noLayOut.includes(path) && <Footer />} */}
      </body>
    </html>
  );
}
